spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://172.16.0.17:5432/ecommerce201707C_satohiro
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: nakanon.41@gmail.com
    password: djzrpsembfnfwsbgs
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
server:
  context-path: /sugar_pizza
  
security.basic.enabled: false